apiVersion: apps/v1
kind: Deployment
metadata:
  name: back-end
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: abdelrahman58/final-project-iti
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: backend-loadblancer
spec:
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
